# Generated by Django 2.2.22 on 2021-05-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_outlay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('operation_name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('currency', models.TextField(max_length=4)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
