# Generated by Django 2.2.22 on 2021-06-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_outlay', '0002_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='statement',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
