# Generated by Django 2.2.22 on 2021-06-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_outlay', '0003_auto_20210601_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='my_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_outlay.Category'),
        ),
    ]
